// AUTOGENERATED - DO NOT MODIFY

// View component imports — one per viewport declared in ui_extension.views
import App from '../src/views/App';

// Exposes the SDK version so the Dashboard can verify compatibility
export * from '@stripe/ui-extension-sdk/version';

// Named exports make each view component accessible to the Dashboard runtime

export { 
  App
 };

// Timestamp changes on every export, ensuring the dev server detects a rebuild
export const BUILD_TIME = '2026-06-04 18:50:48.271755 +0530 IST m=+3.072281918';

// App manifest — consumed by the Dashboard to configure the app
export default {
  "$schema": "https://stripe.com/stripe-app.schema.json",
  "distribution_type": "private",
  "icon": "./bridge_icon_32.png",
  "id": "com.bridge.payment-sync",
  "name": "Bridge",
  "permissions": [
    {
      "permission": "payment_records_write",
      "purpose": "Sync PayPal (and other processor) transactions into Stripe Payment Records API so all revenue appears in Stripe."
    },
    {
      "permission": "payment_records_read",
      "purpose": "Read existing payment records to verify sync status and avoid duplicate pushes."
    },
    {
      "permission": "balance_read",
      "purpose": "Display synced transaction summaries in the Bridge dashboard panel."
    }
  ],
  "sandbox_install_compatible": true,
  "stripe_api_access_type": "platform",
  "ui_extension": {
    "content_security_policy": {
      "connect-src": [
        "https://bridge-production-ad61.up.railway.app/api/",
        "https://api-m.sandbox.paypal.com/v2/",
        "https://api-m.paypal.com/v2/"
      ],
      "purpose": "Allow Bridge to connect to its backend server and PayPal API."
    },
    "views": [
      {
        "component": "App",
        "viewport": "stripe.dashboard.home.overview"
      }
    ]
  },
  "version": "0.1.0"
};
