// AUTOGENERATED - DO NOT MODIFY

// View component imports — one per viewport declared in ui_extension.views
import App from '../src/views/App';

// Exposes the SDK version so the Dashboard can verify compatibility
export * from '@stripe/ui-extension-sdk/version';

// Named exports make each view component accessible to the Dashboard runtime

export { 
  App
 };

// Timestamp changes on every export, ensuring the dev server detects a rebuild
export const BUILD_TIME = '2026-06-05 01:24:55.296607 +0530 IST m=+1.700470876';

// App manifest — consumed by the Dashboard to configure the app
export default {
  "$schema": "https://stripe.com/stripe-app.schema.json",
  "distribution_type": "private",
  "icon": "./bridge_icon_32.png",
  "id": "com.bridge.payment-sync",
  "name": "Bridge",
  "permissions": [
    {
      "permission": "payment_records_write",
      "purpose": "Sync PayPal transactions into Stripe Payment Records API so all revenue appears in Stripe."
    },
    {
      "permission": "payment_records_read",
      "purpose": "Read existing payment records to verify sync status and avoid duplicate pushes."
    },
    {
      "permission": "balance_read",
      "purpose": "Display synced transaction summaries in the Bridge dashboard."
    }
  ],
  "sandbox_install_compatible": true,
  "stripe_api_access_type": "platform",
  "ui_extension": {
    "content_security_policy": {
      "connect-src": [
        "https://bridge-production-ad61.up.railway.app/api/",
        "https://bridge-production-ad61.up.railway.app/app"
      ],
      "purpose": "Allow Bridge to connect to its backend server for sync operations."
    },
    "views": [
      {
        "component": "App",
        "viewport": "stripe.dashboard.drawer.default"
      }
    ]
  },
  "version": "0.3.1"
};
